### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by sokatra** [r57zone/notifications#1]
Hy, nice program, but i am missing a timer .. and some other features, but a timer is the most important
an ok and cancel button would also be nice and errorlevel should be returned (ok pressed or cancel)

Some Inspiration
https://github.com/cubiclesoft/messagebox-windows
https://www.paralint.com/projects/notifu/

**Comment by r57zone** [comment]
Hi, I didn't quite understand about the timer. Do you want the notification to be displayed after some time?

**Comment by sokatra** [comment]
Hy, i mean a setting where i can change the time how long the message will be displayed.so somebody can use your tool in a deployment task .. shows a message for about 20 min. or until somebody clicks on ok.
Your message is disappearing after seconds .. the user can't read it if he is not sitting in front of his pc.

For example i can send a message to the user "please restart your pc to apply patches" .. 
in my first link the program messagebox-windows has therefore the parameter 
 /w=Milliseconds
                The amount of time, in milliseconds, to wait.
notifu has the following parameter
/d <value>	The number of milliseconds to display (omit or 0 for infinit)


Kind regards
sokatra

**Comment by r57zone** [comment]
I added the ability to increase the display of the notification. To do this, add the "-ms 10000" startup parameter, where 10000 is 10 seconds in milliseconds.

As for the buttons, I'll think about it, maybe will be added later.

Latest version: https://github.com/r57zone/Notifications/releases

Also, in order not to miss events, you can use an alternative notification center - https://github.com/r57zone/Notification-center#notification-center
