### ISSUE TITLE
network scan

### ISSUE THREAD

**Issue by sokatra** [r57zone/Notifications#2]
hy, can you please explain why your program doing many arp Broadcast requests?

**Comment by r57zone** [comment]
ARP https://en.wikipedia.org/wiki/Address_Resolution_Protocol ?  The program only makes a request to the registry to write the path to the program there. It does not make any ARP requests and does not interact in any way with the Internet or network protocols. All [source code is available](https://github.com/r57zone/Notifications/blob/master/Source/Unit1.pas), you can see for yourself.
